#!/bin/sh
while read oldrev newrev refname
do
    # We only really care about making sure everything compiles when going into
    # the master branch so...
    if [[ $refname = "refs/heads/master" ]] ; then
        echo "Ensuring a release build can be successfully compiled..."
        make prepush && echo "Release builds ok." || echo "Release builds failed. Please ensure build succeeds before pushing to Master on Github"
done

# All is well, lets return 0 to push to github
exit 0
